### ISSUE TITLE
프로젝트 초기 설정

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/musinsa#1]
## 📃 Description

CRA 및 프로젝트 진행에 필요한 라이브러리를 설치하는 등 환경 설정을 진행한다.

## ☑ Todo
- [x] CRA
- [x] ESLint, Prettier 설정
- [x] 절대 경로 설정
- [x] 스토리북 설치 및 설정
- [x] GlobalStyle, theme 설정
