### ISSUE TITLE
유저는 검색창에 입력한 값으로 상품을 필터링할 수 있다.

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/musinsa#10]
## 📃 Description

[스토리 2](https://github.com/mina-gwak/musinsa/wiki/%EC%9A%94%EA%B5%AC%EC%82%AC%ED%95%AD-%EB%B6%84%EC%84%9D#%EC%8A%A4%ED%86%A0%EB%A6%AC-2)를 구현한다.

## ☑ Todo
- [x] 검색창에 값이 입력되면 창 우측에 입력값을 초기화할 수 있는 X 버튼이 생성된다.
- [x] X 버튼을 누르면 입력했던 값이 초기화된다.
- [x] 유저가 값을 입력하고 엔터를 누르면 데이터를 필터링한다.
  - [x] 입력된 값이 활성화된 필터 목록에 추가된다. (이미 존재하는 값이면 추가하지 않는다.)
  - [x] 검색창의 값이 초기화되고, focus 상태가 된다.
  - [x] 추가된 필터를 포함하여 상품 데이터를 필터링한 후 렌더링한다.
