### ISSUE TITLE
유저는 필터를 클릭해 필터링된 상품 리스트를 조회할 수 있다.

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/musinsa#11]
## 📃 Description

[스토리 3](https://github.com/mina-gwak/musinsa/wiki/%EC%9A%94%EA%B5%AC%EC%82%AC%ED%95%AD-%EB%B6%84%EC%84%9D#%EC%8A%A4%ED%86%A0%EB%A6%AC-3)을 구현한다.

## ☑ Todo
- [x] 각 필터를 클릭하면 해당 값으로 데이터를 필터링한다.
  - [x] 해당 필터의 글자의 색상이 파랗게 표시된다.
  - [x] 해당 필터가 활성화된 필터 목록에 추가된다.
  - [x] 검색창이 열려있는 상태였을 경우 닫힌 상태로 변경된다.
  - [x] 추가된 필터를 포함하여 상품 데이터를 필터링한 후 렌더링한다.
- [x] 필터를 다시 클릭하면 필터가 제거된다.
  - [x] 필터의 글자 색상이 원래대로 돌아온다.
  - [x] 필터가 활성화된 필터 목록에서 제거된다.
  - [x] 활성화된 필터가 하나도 존재하지 않을 경우 활성화된 필터 영역이 사라진다.
  - [x] 해당 필터를 제외한 필터들로 상품 데이터를 필터링한 후 렌더링한다. 필터가 존재하지 않는다면 모든 상품 데이터를 렌더링한다.
