### ISSUE TITLE
유저는 활성화된 필터를 클릭해 필터를 제거할 수 있다.

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/musinsa#13]
## 📃 Description

[스토리 5](https://github.com/mina-gwak/musinsa/wiki/%EC%9A%94%EA%B5%AC%EC%82%AC%ED%95%AD-%EB%B6%84%EC%84%9D#%EC%8A%A4%ED%86%A0%EB%A6%AC-5)를 구현한다.

## ☑ Todo
- [x] 활성화된 필터를 클릭하면 필터가 제거된다.
  - [x] 필터를 클릭하면 활성화된 필터 목록에서 해당 필터가 사라진다.
  - [x] 사용자가 입력한 값인 경우 검색 버튼이 원래대로 돌아온다.
  - [x] 필터 목록에서 선택한 값인 경우 해당 필터가 원래대로 돌아온다.
  - [x] 활성화된 필터가 하나도 존재하지 않을 경우 활성화된 필터 영역이 사라진다.
  - [x] 해당 필터를 제외한 필터들로 상품 데이터를 필터링한 후 렌더링한다. 필터가 존재하지 않는다면 모든 상품 데이터를 렌더링한다.
