### ISSUE TITLE
Header 영역

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/musinsa#3]
## 📃 Description

<img width="1174" alt="스크린샷 2022-07-14 오후 8 45 29" src="https://user-images.githubusercontent.com/62706988/178975196-acd27193-4656-48d2-92d9-b1898bd882b9.png" />
헤더 영역을 생성한다.

## ☑ Todo
- [x] 필터 옵션 (Filter Options)
  - [x] 검색 버튼 (Search Button)
  - [x] 필터 (Filter)
- [x] 검색창 (Search Field)
- [x] 활성화된 필터 목록 (Active Filters)
  - [x] 활성화된 필터 (Active Filter)
  - [x] 새로고침 버튼 (Refresh Button)
