### ISSUE TITLE
유저는 검색 버튼을 눌러 검색창을 열고 닫을 수 있다.

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/musinsa#9]
## 📃 Description

[스토리 1](https://github.com/mina-gwak/musinsa/wiki/%EC%9A%94%EA%B5%AC%EC%82%AC%ED%95%AD-%EB%B6%84%EC%84%9D#%EC%8A%A4%ED%86%A0%EB%A6%AC-1)을 구현한다.

## ☑ Todo
- [x] 검색 버튼을 클릭하면 검색 버튼이 파란색으로 변한다.
  - [x] 필터 영역 하단에 상품을 검색할 수 있는 검색 영역이 렌더링된다.
  - [x] 검색바에 focus가 되어 바로 검색창에 입력할 수 있다.
- [x] 검색 버튼을 다시 클릭하면 검색 버튼이 원래대로 돌아온다.
  - [ ] 단, 검색창에 입력한 값이 필터에 존재하는 경우 ‘검색’ 글자의 색상이 파랗게 표시된다.
  - [x] 필터 영역 하단의 검색창이 사라진다.
